import type { TtsVoice } from "./types";

export const TTS_VOICES: TtsVoice[] = [
	// ==========================================
	// --- TIẾNG VIỆT (14 Giọng Độc Đáo) ---
	// ==========================================
	{
		id: "vi-female-sweet",
		name: "Cô gái trẻ (Hoài My)",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "trending"],
		description: "Trong trẻo, ngọt ngào, giọng nữ Bắc chuẩn TikTok",
		avatarGradient: "from-pink-500 via-rose-500 to-red-400",
		avatarIcon: "🌸",
		previewSampleText: "Xin chào! Mình là giọng đọc cô gái trẻ ngọt ngào, rất vui được lồng tiếng cho video của bạn.",
		engine: "edge",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		langCode: "vi",
		pitchHz: 40,
		rateMultiplier: 1.08,
	},
	{
		id: "vi-male-warm",
		name: "Chàng trai ấm áp (Nam Minh)",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "trending", "story"],
		description: "Trầm ấm, truyền cảm, cuốn hút và nam tính",
		avatarGradient: "from-blue-600 via-indigo-500 to-cyan-400",
		avatarIcon: "🎙️",
		previewSampleText: "Chào bạn, đây là giọng nam trầm ấm, hoàn hảo cho những thước phim sâu lắng và podcast.",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: -25,
		rateMultiplier: 0.96,
	},
	{
		id: "vi-female-google",
		name: "Chị Google (Huyền thoại)",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "trending"],
		description: "Giọng đọc thông báo tự nhiên, quen thuộc trên mạng xã hội",
		avatarGradient: "from-amber-400 via-orange-500 to-yellow-500",
		avatarIcon: "📢",
		previewSampleText: "Xin chào các bạn! Tôi là chị Google, giọng đọc huyền thoại của các video viral trên mạng xã hội.",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.0,
		rateOffset: 1.0,
	},
	{
		id: "vi-female-news",
		name: "MC Thời sự Nữ",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "story"],
		description: "Phát thanh viên chuẩn mực, lưu loát, dứt khoát",
		avatarGradient: "from-teal-600 via-emerald-600 to-cyan-600",
		avatarIcon: "📺",
		previewSampleText: "Kính chào quý vị và các bạn. Đây là bản tin thời sự được phát thanh bởi Cắt Chim.",
		engine: "edge",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		langCode: "vi",
		pitchHz: 0,
		rateMultiplier: 1.0,
	},
	{
		id: "vi-male-news",
		name: "MC Thời sự Nam",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "story"],
		description: "Đĩnh đạc, rõ ràng, phong cách truyền hình trang trọng",
		avatarGradient: "from-slate-700 via-teal-700 to-emerald-600",
		avatarIcon: "📰",
		previewSampleText: "Chào mừng quý khán giả đến với chương trình tin tức tổng hợp đặc biệt hôm nay.",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: 5,
		rateMultiplier: 1.02,
	},
	{
		id: "vi-female-soft",
		name: "Lan Chi (Dịu dàng / ASMR)",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "story"],
		description: "Nhẹ nhàng, êm dịu, du dương cho tâm sự và thư giãn",
		avatarGradient: "from-violet-500 via-purple-500 to-pink-500",
		avatarIcon: "🍃",
		previewSampleText: "Hãy nhắm mắt lại và thả lỏng tâm hồn, cùng tận hưởng những khoảnh khắc bình yên này nhé.",
		engine: "edge",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		langCode: "vi",
		pitchHz: -15,
		rateMultiplier: 0.88,
	},
	{
		id: "vi-male-vlog",
		name: "Tuấn Anh (Vlogger Năng động)",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "trending"],
		description: "Nhiệt huyết, nhanh nhẹn, tươi vui cho video review & vlog",
		avatarGradient: "from-emerald-500 via-teal-600 to-cyan-500",
		avatarIcon: "🚀",
		previewSampleText: "Hello xin chào tất cả anh em! Chào mừng anh em đã quay trở lại với video siêu hấp dẫn ngày hôm nay!",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: 30,
		rateMultiplier: 1.15,
	},
	{
		id: "vi-male-story",
		name: "Bác An (Kể chuyện Cổ tích)",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "story"],
		description: "Trầm khàn, chậm rãi, phong cách ông lão kể chuyện cổ tích xưa",
		avatarGradient: "from-amber-700 via-yellow-800 to-amber-900",
		avatarIcon: "🧙",
		previewSampleText: "Ngày xửa ngày xưa, ở một ngôi làng cổ nọ, có những điều kỳ diệu mà ta sắp kể cho các con nghe...",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: -60,
		rateMultiplier: 0.82,
	},
	{
		id: "vi-child-girl",
		name: "Bé Bông (Đáng yêu)",
		language: "vi-VN",
		gender: "child",
		categories: ["vietnamese", "fun"],
		description: "Giọng bé gái hoạt hình lí lắc, dễ thương và hồn nhiên",
		avatarGradient: "from-lime-400 via-green-500 to-emerald-400",
		avatarIcon: "👧",
		previewSampleText: "A ha! Xin chào các bạn nhỏ, hôm nay tụi mình cùng nhau đi chơi công viên nha!",
		engine: "edge",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		langCode: "vi",
		pitchHz: 85,
		rateMultiplier: 1.15,
	},
	{
		id: "vi-child-boy",
		name: "Bé Bo (Tinh nghịch)",
		language: "vi-VN",
		gender: "child",
		categories: ["vietnamese", "fun"],
		description: "Giọng bé trai hóm hỉnh, tò mò, khám phá thế giới",
		avatarGradient: "from-cyan-400 via-sky-500 to-blue-500",
		avatarIcon: "👦",
		previewSampleText: "Chào các bạn! Tớ là bé Bo, siêu nhân tinh nghịch đây!",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: 70,
		rateMultiplier: 1.12,
	},
	{
		id: "vi-intl-male",
		name: "Alex (Việt Kiều Trẻ)",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "trending"],
		description: "Phong cách hiện đại, phóng khoáng, ngữ điệu quốc tế",
		avatarGradient: "from-blue-700 via-indigo-600 to-violet-500",
		avatarIcon: "🕶️",
		previewSampleText: "Xin chào mọi người, tôi là Alex, rất hào hứng được đồng hành cùng dự án sáng tạo của các bạn.",
		engine: "edge",
		edgeVoiceName: "en-US-AndrewMultilingualNeural",
		langCode: "vi",
		pitchHz: 5,
		rateMultiplier: 1.04,
	},
	{
		id: "vi-intl-female",
		name: "Chloe (Việt Kiều Nữ)",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "trending"],
		description: "Sang chảnh, tươi tắn, thời thượng cho vlog du lịch & phong cách",
		avatarGradient: "from-rose-400 via-fuchsia-500 to-purple-600",
		avatarIcon: "✨",
		previewSampleText: "Hi các bạn! Chloe đây nè, hôm nay mình sẽ dẫn mọi người trải nghiệm một ngày thật tuyệt vời nhé!",
		engine: "edge",
		edgeVoiceName: "en-US-AvaMultilingualNeural",
		langCode: "vi",
		pitchHz: 15,
		rateMultiplier: 1.02,
	},
	{
		id: "vi-male-brian",
		name: "Brian (Thuyết minh Phim)",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "story"],
		description: "Giọng đọc phim tài liệu sâu lắng, cuốn hút người nghe",
		avatarGradient: "from-stone-700 via-zinc-800 to-neutral-900",
		avatarIcon: "🎬",
		previewSampleText: "Vào những thời khắc quyết định của lịch sử, con người luôn tìm thấy sức mạnh phi thường bên trong mình.",
		engine: "edge",
		edgeVoiceName: "en-US-BrianMultilingualNeural",
		langCode: "vi",
		pitchHz: -15,
		rateMultiplier: 0.94,
	},
	{
		id: "vi-female-emma",
		name: "Emma (Thanh lịch)",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese"],
		description: "Trang nhã, từ tốn, phong thái quý cô tinh tế",
		avatarGradient: "from-amber-200 via-yellow-400 to-orange-400",
		avatarIcon: "👒",
		previewSampleText: "Kính chào quý vị, nghệ thuật và cái đẹp luôn bắt đầu từ những chi tiết giản đơn nhất.",
		engine: "edge",
		edgeVoiceName: "en-US-EmmaMultilingualNeural",
		langCode: "vi",
		pitchHz: 0,
		rateMultiplier: 0.98,
	},

	// ==========================================
	// --- TIẾNG ANH (8 Giọng Tự Nhiên) ---
	// ==========================================
	{
		id: "en-female-jenny",
		name: "Jenny - Sweet US",
		language: "en-US",
		gender: "female",
		categories: ["english", "trending"],
		description: "Natural, friendly, expressive American female voice",
		avatarGradient: "from-fuchsia-500 via-pink-500 to-rose-400",
		avatarIcon: "👱‍♀️",
		previewSampleText: "Hello there! I'm Jenny, ready to bring your video scripts to life with great energy.",
		engine: "edge",
		edgeVoiceName: "en-US-JennyNeural",
		langCode: "en",
		pitchHz: 5,
		rateMultiplier: 1.0,
	},
	{
		id: "en-male-guy",
		name: "Guy - Casual US",
		language: "en-US",
		gender: "male",
		categories: ["english", "trending"],
		description: "Dynamic, confident, casual American male voice for vlogs",
		avatarGradient: "from-blue-500 via-sky-500 to-indigo-500",
		avatarIcon: "👱‍♂️",
		previewSampleText: "What's up everyone! This is Guy, your go-to voice for modern and punchy content.",
		engine: "edge",
		edgeVoiceName: "en-US-GuyNeural",
		langCode: "en",
		pitchHz: 0,
		rateMultiplier: 1.02,
	},
	{
		id: "en-female-aria",
		name: "Aria - Professional",
		language: "en-US",
		gender: "female",
		categories: ["english", "story"],
		description: "Clear, authoritative and polished for commercials and promos",
		avatarGradient: "from-purple-600 via-indigo-600 to-violet-500",
		avatarIcon: "👩‍💼",
		previewSampleText: "Discover the ultimate creative freedom with high precision video editing.",
		engine: "edge",
		edgeVoiceName: "en-US-AriaNeural",
		langCode: "en",
		pitchHz: 10,
		rateMultiplier: 0.98,
	},
	{
		id: "en-male-deep",
		name: "Davis - Deep Cinema",
		language: "en-US",
		gender: "male",
		categories: ["english", "story"],
		description: "Deep, cinematic and resonant voice for trailers & audiobooks",
		avatarGradient: "from-gray-800 via-slate-700 to-zinc-600",
		avatarIcon: "🧔",
		previewSampleText: "In the depths of winter, I finally learned that within me there lay an invincible summer.",
		engine: "edge",
		edgeVoiceName: "en-US-ChristopherNeural",
		langCode: "en",
		pitchHz: -35,
		rateMultiplier: 0.90,
	},
	{
		id: "en-female-emma",
		name: "Emma - Sophisticated",
		language: "en-US",
		gender: "female",
		categories: ["english"],
		description: "Elegant and articulate American English narrator",
		avatarGradient: "from-amber-500 via-orange-500 to-red-500",
		avatarIcon: "💎",
		previewSampleText: "Excellence is not an act, but a habit cultivated through dedication.",
		engine: "edge",
		edgeVoiceName: "en-US-EmmaNeural",
		langCode: "en",
		pitchHz: 0,
		rateMultiplier: 0.98,
	},
	{
		id: "en-male-brian",
		name: "Brian - Storyteller",
		language: "en-US",
		gender: "male",
		categories: ["english", "story"],
		description: "Warm, comforting voice for bedtime stories and history",
		avatarGradient: "from-emerald-700 via-teal-800 to-slate-900",
		avatarIcon: "📚",
		previewSampleText: "Every great journey begins with a single step into the unknown.",
		engine: "edge",
		edgeVoiceName: "en-US-BrianNeural",
		langCode: "en",
		pitchHz: -15,
		rateMultiplier: 0.95,
	},
	{
		id: "en-male-ryan",
		name: "Ryan - British Gentleman",
		language: "en-GB",
		gender: "male",
		categories: ["english"],
		description: "Smooth, articulate and sophisticated British English accent",
		avatarGradient: "from-teal-600 via-cyan-600 to-blue-600",
		avatarIcon: "🇬🇧",
		previewSampleText: "Good day to you. It is a genuine pleasure to assist with your video production today.",
		engine: "edge",
		edgeVoiceName: "en-GB-RyanNeural",
		langCode: "en-gb",
		pitchHz: 0,
		rateMultiplier: 0.96,
	},
	{
		id: "en-female-sonia",
		name: "Sonia - British Lady",
		language: "en-GB",
		gender: "female",
		categories: ["english"],
		description: "Refined and polished BBC-style British female voice",
		avatarGradient: "from-indigo-600 via-purple-600 to-pink-600",
		avatarIcon: "👑",
		previewSampleText: "Welcome to this broadcast. Here is an overview of today's key developments.",
		engine: "edge",
		edgeVoiceName: "en-GB-SoniaNeural",
		langCode: "en-gb",
		pitchHz: 5,
		rateMultiplier: 1.0,
	},

	// ==========================================
	// --- HIỆU ỨNG & VUI NHỘN (4 Giọng Biến Âm) ---
	// ==========================================
	{
		id: "special-chipmunk",
		name: "Sóc chuột vui nhộn (Chipmunk)",
		language: "vi-VN",
		gender: "special",
		categories: ["fun", "trending"],
		description: "Giọng tí hon cao vút, lí lắc cực kỳ hài hước và giải trí",
		avatarGradient: "from-orange-500 via-red-500 to-pink-500",
		avatarIcon: "🐿️",
		previewSampleText: "Hi hi! Mình là sóc chuột nhỏ đây nè, nghe giọng mình lí lắc có buồn cười hông nè!",
		engine: "edge",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		langCode: "vi",
		pitchHz: 140,
		rateMultiplier: 1.35,
		audioEffect: "chipmunk",
	},
	{
		id: "special-robot",
		name: "Người máy Robot AI",
		language: "vi-VN",
		gender: "special",
		categories: ["fun"],
		description: "Giọng điện tử viễn tưởng công nghệ số chuẩn người máy",
		avatarGradient: "from-cyan-500 via-blue-600 to-slate-800",
		avatarIcon: "🤖",
		previewSampleText: "Hệ thống trí tuệ nhân tạo Cắt Chim đã sẵn sàng kích hoạt lệnh của bạn.",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: -35,
		rateMultiplier: 1.08,
		audioEffect: "robot",
	},
	{
		id: "special-titan",
		name: "Chiến Binh Titan (Trầm vang)",
		language: "vi-VN",
		gender: "special",
		categories: ["fun", "story"],
		description: "Giọng quái vật / khổng lồ uy lực rung chuyển màn ảnh",
		avatarGradient: "from-stone-900 via-red-950 to-neutral-900",
		avatarIcon: "🗿",
		previewSampleText: "Kẻ nào dám đánh thức sức mạnh bóng tối của Titan ngàn năm!",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: -90,
		rateMultiplier: 0.78,
		audioEffect: "deep-bass",
	},
	{
		id: "special-radio",
		name: "Loa phát thanh Vintage",
		language: "vi-VN",
		gender: "special",
		categories: ["fun"],
		description: "Giọng đàm thoại qua radio cảnh sát / loa phát thanh cổ",
		avatarGradient: "from-amber-600 via-stone-700 to-zinc-800",
		avatarIcon: "📻",
		previewSampleText: "Alo, 1 2 3 4 nghe rõ trả lời! Đây là thông báo khẩn cấp từ trung tâm chỉ huy.",
		engine: "edge",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		langCode: "vi",
		pitchHz: 15,
		rateMultiplier: 1.05,
		audioEffect: "radio",
	},
];
