import type { TtsVoice } from "./types";

export const TTS_VOICES: TtsVoice[] = [
	// --- Tiếng Việt ---
	{
		id: "vi-female-sweet",
		name: "Cô gái trẻ",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "trending"],
		description: "Trong trẻo, ngọt ngào, giọng nữ Bắc chuẩn TikTok",
		avatarGradient: "from-pink-500 via-rose-500 to-red-400",
		avatarIcon: "🌸",
		previewSampleText: "Xin chào! Đây là giọng đọc cô gái trẻ, rất vui được lồng tiếng cho video của bạn.",
		engine: "google",
		langCode: "vi",
		edgeVoiceName: "vi-VN-HoaiMyNeural",
		pitchOffset: 1.08,
		rateOffset: 1.02,
	},
	{
		id: "vi-male-warm",
		name: "Chàng trai ấm áp",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "trending", "story"],
		description: "Trầm ấm, truyền cảm, cuốn hút và nam tính",
		avatarGradient: "from-blue-600 via-indigo-500 to-cyan-400",
		avatarIcon: "🎙️",
		previewSampleText: "Chào bạn, đây là giọng nam trầm ấm, hoàn hảo cho những thước phim sâu lắng.",
		engine: "google",
		langCode: "vi",
		edgeVoiceName: "vi-VN-NamMinhNeural",
		pitchOffset: 0.94,
		rateOffset: 0.98,
	},
	{
		id: "vi-female-google",
		name: "Chị Google",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese", "trending"],
		description: "Giọng đọc thông báo tự nhiên, quen thuộc trên mạng xã hội",
		avatarGradient: "from-amber-400 via-orange-500 to-yellow-500",
		avatarIcon: "📢",
		previewSampleText: "Xin chào các bạn! Tôi là chị Google, giọng đọc huyền thoại của các video viral.",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.0,
		rateOffset: 1.0,
	},
	{
		id: "vi-male-news",
		name: "MC Thời sự",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "story"],
		description: "Đĩnh đạc, rõ ràng, phong cách phát thanh viên truyền hình",
		avatarGradient: "from-slate-700 via-teal-700 to-emerald-600",
		avatarIcon: "📰",
		previewSampleText: "Kính chào quý vị và các bạn. Đây là bản tin tổng hợp được phát thanh bởi Cắt Chim.",
		engine: "google",
		langCode: "vi",
		pitchOffset: 0.96,
		rateOffset: 1.04,
	},
	{
		id: "vi-male-south",
		name: "Thanh niên miền Nam",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "trending"],
		description: "Hào sảng, vui tươi, đậm chất Nam Bộ gần gũi",
		avatarGradient: "from-emerald-500 via-teal-600 to-cyan-500",
		avatarIcon: "🌾",
		previewSampleText: "Bữa nay có gì vui hông bà con? Giọng miền Nam này nghe là thấy cưng liền nè!",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.02,
		rateOffset: 1.05,
	},
	{
		id: "vi-female-south",
		name: "Cô gái miền Nam",
		language: "vi-VN",
		gender: "female",
		categories: ["vietnamese"],
		description: "Dịu dàng, dễ thương, ngọt ngào và mến khách",
		avatarGradient: "from-violet-500 via-purple-500 to-pink-500",
		avatarIcon: "🌺",
		previewSampleText: "Dạ em chào anh chị nha, giọng con gái miền Tây dễ thương dữ lắm nè.",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.12,
		rateOffset: 1.0,
	},
	{
		id: "vi-male-story",
		name: "Ông lão cổ tích",
		language: "vi-VN",
		gender: "male",
		categories: ["vietnamese", "story"],
		description: "Trầm bổng, chậm rãi, phong cách kể chuyện truyền kỳ xưa",
		avatarGradient: "from-amber-700 via-yellow-800 to-amber-900",
		avatarIcon: "🧙",
		previewSampleText: "Ngày xửa ngày xưa, ở một ngôi làng nọ, có những điều kỳ diệu mà ta sắp kể cho các con nghe...",
		engine: "google",
		langCode: "vi",
		pitchOffset: 0.86,
		rateOffset: 0.88,
	},
	{
		id: "vi-child-fun",
		name: "Em bé hoạt hình",
		language: "vi-VN",
		gender: "child",
		categories: ["vietnamese", "fun"],
		description: "Tươi vui, ngộ nghĩnh, lí lắc và hồn nhiên",
		avatarGradient: "from-lime-400 via-green-500 to-emerald-400",
		avatarIcon: "👶",
		previewSampleText: "A ha! Xin chào các bạn nhỏ, hôm nay tụi mình cùng khám phá thế giới nha!",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.35,
		rateOffset: 1.1,
	},

	// --- Tiếng Anh ---
	{
		id: "en-female-jenny",
		name: "Jenny - Sweet US",
		language: "en-US",
		gender: "female",
		categories: ["english", "trending"],
		description: "Natural, friendly, expressive American female voice",
		avatarGradient: "from-fuchsia-500 via-pink-500 to-rose-400",
		avatarIcon: "👱‍♀️",
		previewSampleText: "Hello there! I'm Jenny, ready to bring your video scripts to life with great energy.",
		engine: "google",
		langCode: "en",
		pitchOffset: 1.05,
		rateOffset: 1.0,
	},
	{
		id: "en-male-guy",
		name: "Guy - Casual US",
		language: "en-US",
		gender: "male",
		categories: ["english", "trending"],
		description: "Dynamic, confident, casual American male voice for vlogs",
		avatarGradient: "from-blue-500 via-sky-500 to-indigo-500",
		avatarIcon: "👱‍♂️",
		previewSampleText: "What's up everyone! This is Guy, your go-to voice for modern and punchy content.",
		engine: "google",
		langCode: "en",
		pitchOffset: 0.95,
		rateOffset: 1.03,
	},
	{
		id: "en-female-aria",
		name: "Aria - Professional",
		language: "en-US",
		gender: "female",
		categories: ["english", "story"],
		description: "Clear, authoritative and polished for commercials and promos",
		avatarGradient: "from-purple-600 via-indigo-600 to-violet-500",
		avatarIcon: "👩‍💼",
		previewSampleText: "Discover the ultimate creative freedom with high precision video editing.",
		engine: "google",
		langCode: "en",
		pitchOffset: 1.0,
		rateOffset: 0.98,
	},
	{
		id: "en-male-christopher",
		name: "Christopher - Narrative",
		language: "en-US",
		gender: "male",
		categories: ["english", "story"],
		description: "Deep, cinematic and resonant voice for audiobooks & documentaries",
		avatarGradient: "from-gray-800 via-slate-700 to-zinc-600",
		avatarIcon: "🧔",
		previewSampleText: "In the depths of winter, I finally learned that within me there lay an invincible summer.",
		engine: "google",
		langCode: "en",
		pitchOffset: 0.88,
		rateOffset: 0.92,
	},
	{
		id: "en-child-ana",
		name: "Ana - Cartoon Kid",
		language: "en-US",
		gender: "child",
		categories: ["english", "fun"],
		description: "Playful, cute and upbeat voice for animation and games",
		avatarGradient: "from-yellow-400 via-amber-400 to-orange-400",
		avatarIcon: "👧",
		previewSampleText: "Yay! Let's go on an amazing adventure together right now!",
		engine: "google",
		langCode: "en",
		pitchOffset: 1.3,
		rateOffset: 1.08,
	},
	{
		id: "en-male-ryan",
		name: "Ryan - British Polite",
		language: "en-GB",
		gender: "male",
		categories: ["english"],
		description: "Smooth, articulate and sophisticated British English accent",
		avatarGradient: "from-teal-600 via-cyan-600 to-blue-600",
		avatarIcon: "🇬🇧",
		previewSampleText: "Good day to you. It's a genuine pleasure to assist with your video production.",
		engine: "google",
		langCode: "en-gb",
		pitchOffset: 0.98,
		rateOffset: 0.96,
	},

	// --- Hiệu ứng đặc biệt ---
	{
		id: "special-robot",
		name: "Người máy Robot",
		language: "vi-VN",
		gender: "special",
		categories: ["fun"],
		description: "Giọng điện tử viễn tưởng công nghệ số",
		avatarGradient: "from-cyan-500 via-blue-600 to-slate-800",
		avatarIcon: "🤖",
		previewSampleText: "Hệ thống trí tuệ nhân tạo Cắt Chim đã sẵn sàng kích hoạt lệnh của bạn.",
		engine: "google",
		langCode: "vi",
		pitchOffset: 0.8,
		rateOffset: 1.15,
	},
	{
		id: "special-chipmunk",
		name: "Sóc chuột vui nhộn",
		language: "vi-VN",
		gender: "special",
		categories: ["fun", "trending"],
		description: "Giọng tí hon hài hước, giải trí tốc độ cao",
		avatarGradient: "from-orange-500 via-red-500 to-pink-500",
		avatarIcon: "🐿️",
		previewSampleText: "Hi hi! Mình là sóc chuột nhỏ đây nè, nghe giọng mình có hài hước không nè!",
		engine: "google",
		langCode: "vi",
		pitchOffset: 1.5,
		rateOffset: 1.25,
	},
];
